version: '3.1'
services:

  gobarber-db:
    container_name: gobarber-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

  gobarber-nosql:
    container_name: gobarber-nosql
    image: mongo
    ports:
      - 27017:27017

volumes:
  database-data:
